### ISSUE TITLE
Part2: Cannot connect the API to the SQL database.

### ISSUE THREAD

**Issue by KevinGouji** [NileshGule/AKS-learning-series#3] opened 2018-11-26 02:10 UTC
After running the docker-compose command, the web, api and sql images are up and running. But I can't get the content in sql database: An error occurred using the connection to database 'TechTalksDB'.

**Comment by KevinGouji** [comment] 2018-11-26 03:18
I solved this issue by using Azure data studio instead of sql management tool. Because the latter has a connectivity problem. Running the docker image first, and then using the connection credentials to login to Azure data studio. choose the sql authentication. If you are running your data locally, server name should be your ip address, and user name should be sa.

**Comment by NileshGule** [comment] 2018-11-27 13:38
Thanks @KevinGouji for highlighting the issue. The sa user is default user in the SQL Server 2017 Linux image. Since the issue is resolved I will close it.

**Closed as completed by NileshGule** 2018-11-27 13:38 UTC
